title: AcademTeX
logo: 
description: LaTeX and other templates for academics 
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: true
  owner_url: "https://github.com/AcademTeX"
